[package]
name = "cargo-fix"
version = "0.1.0"
authors = ["Pascal Hertleif <killercup@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/killercup/cargo-fix"
description = "I'm just a placeholder! `cargo install rustfix` instead!"
